# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [19]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [20]:
csv_path = "../output_data/cities.csv"
vacay_df = pd.read_csv(csv_path)
vacay_df = vacay_df.drop('Unnamed: 0', axis=1)
vacay_df.head()

,ID,city,lat,lng,temp,humidity,cloudiness,wind speed,max temp
0,6201424,Mataura,-46.19,168.86,77.65,58,64,0.58,77.65
1,1819729,Hong Kong,22.29,114.16,61.66,77,40,11.41,63.00
2,1507390,Dikson,73.51,80.55,-5.84,95,100,5.39,-5.84
3,2075265,Busselton,-33.65,115.33,90.73,24,97,5.23,93.00
4,4030556,Rikitea,-23.12,-134.97,79.11,77,0,10.22,79.11

In [21]:
# Humidity Heatmap
# Configure gmaps.
# Use the Lat and Lng as locations and Humidity as the weight.
gmaps.configure(api_key=g_key)
locations = vacay_df[["lat", "lng"]]
humidity = vacay_df['humidity'].astype(float)
fig = gmaps.figure()

In [22]:
humidity_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = .5)

fig.add_layer(humidity_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [23]:
vacay_filtered = vacay_df.loc[(vacay_df['temp']<80) & (vacay_df['temp']>70) & (vacay_df['wind speed']<10) & (vacay_df['cloudiness']==0)]

vacay_filtered

,ID,city,lat,lng,temp,humidity,cloudiness,wind speed,max temp
70,3471451,Arraial do Cabo,-22.97,-42.03,75.16,82,0,6.76,75.16
173,3836669,San Rafael,-34.62,-68.33,77.09,28,0,2.57,77.09
185,3867427,Mayor Pablo Lagerenza,-19.93,-60.77,78.64,41,0,4.50,78.64
364,3455756,Osvaldo Cruz,-21.80,-50.88,73.40,69,0,3.36,73.40
448,3860259,Cordoba,-31.41,-64.18,72.97,64,0,5.82,79.00
456,3520161,Sabancuy,18.97,-91.18,70.57,86,0,4.07,70.57
457,1272140,Dwarka,22.24,68.97,71.55,70,0,9.46,71.55

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [24]:
hotel_df = vacay_filtered
hotel_df['Hotel Name'] = ''
hotel_df['address'] = ''
hotel_df

C:\Users\koegs\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\koegs\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,ID,city,lat,lng,temp,humidity,cloudiness,wind speed,max temp,Hotel Name,address
70,3471451,Arraial do Cabo,-22.97,-42.03,75.16,82,0,6.76,75.16,,
173,3836669,San Rafael,-34.62,-68.33,77.09,28,0,2.57,77.09,,
185,3867427,Mayor Pablo Lagerenza,-19.93,-60.77,78.64,41,0,4.50,78.64,,
364,3455756,Osvaldo Cruz,-21.80,-50.88,73.40,69,0,3.36,73.40,,
448,3860259,Cordoba,-31.41,-64.18,72.97,64,0,5.82,79.00,,
456,3520161,Sabancuy,18.97,-91.18,70.57,86,0,4.07,70.57,,
457,1272140,Dwarka,22.24,68.97,71.55,70,0,9.46,71.55,,

In [25]:

params = {
    "rankby": "distance",
    "type": "lodging",
    "key": g_key
    }
    
url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
for index, row in hotel_df.iterrows():

    # get location from df
    target_location = (f"{row['lat']},{row['lng']}")
    target_city = row['city']

    # add location to params dict
    params['location'] = target_location
    
    # assemble url and make API request
    print(f"Retrieving Results for Index {index}: {target_city}.")
    response = requests.get(url, params=params).json()
    
    # extract results
    results = response['results']
    
                       
                       
    try:
        print(f"Closest hotel is {results[0]['name']}.")
        
        hotel_df.loc[index, 'Hotel Name'] = results[0]['name']
        hotel_df.loc[index, 'address'] = results[0]['plus_code']['compound_code']
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
    print("------------")

Retrieving Results for Index 70: Arraial do Cabo.
Closest hotel is Kitchenette Elaine Arraial do Cabo.
------------
Retrieving Results for Index 173: San Rafael.
Closest hotel is Hotel Residencial Independencia.
------------
Retrieving Results for Index 185: Mayor Pablo Lagerenza.
Missing field/result... skipping.
------------
Retrieving Results for Index 364: Osvaldo Cruz.
Closest hotel is Hotel Eldorado.
------------
Retrieving Results for Index 448: Cordoba.
Closest hotel is Hosteria Rivadavia.
------------
Retrieving Results for Index 456: Sabancuy.
Closest hotel is Hotel Aguilar.
------------
Retrieving Results for Index 457: Dwarka.
Closest hotel is Hotel Rajmandir.
------------

In [26]:
hotel_df

,ID,city,lat,lng,temp,humidity,cloudiness,wind speed,max temp,Hotel Name,address
70,3471451,Arraial do Cabo,-22.97,-42.03,75.16,82,0,6.76,75.16,Kitchenette Elaine Arraial do Cabo,"2XJ9+5W Praia Grande, Arraial do Cabo - State ..."
173,3836669,San Rafael,-34.62,-68.33,77.09,28,0,2.57,77.09,Hotel Residencial Independencia,"9MHC+Q4 San Rafael, Mendoza Province, Argentina"
185,3867427,Mayor Pablo Lagerenza,-19.93,-60.77,78.64,41,0,4.50,78.64,,
364,3455756,Osvaldo Cruz,-21.80,-50.88,73.40,69,0,3.36,73.40,Hotel Eldorado,"643F+GF Centro, Osvaldo Cruz - State of São Pa..."
448,3860259,Cordoba,-31.41,-64.18,72.97,64,0,5.82,79.00,Hosteria Rivadavia,"HRQ9+XX Córdoba, Cordoba, Argentina"
456,3520161,Sabancuy,18.97,-91.18,70.57,86,0,4.07,70.57,Hotel Aguilar,"XRCC+4R Sabancuy, Campeche, Mexico"
457,1272140,Dwarka,22.24,68.97,71.55,70,0,9.46,71.55,Hotel Rajmandir,"6XQ9+QR Dwarka, Gujarat, India"

In [27]:
 # NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>Address</dt><dd>{address}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["lat", "lng"]]

In [28]:
# Add marker layer ontop of heat map
hotel_layer = gmaps.symbol_layer(locations, 
                                  fill_color='rgba(0, 150, 0, 0.4)',
                                  stroke_color='rgba(0, 0, 150, 0.4)',
                                  scale=2,
                                 info_box_content = hotel_info)
fig.add_layer(hotel_layer)
fig

# Display Map

Figure(layout=FigureLayout(height='420px'))